/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gaetani' at '12/31/16 10:38 PM' with Gradle 3.2.1
 *
 * @author gaetani, @date 12/31/16 10:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
